### PR TITLE
switch to Font Awesome for icons and brand logos

### PR DESCRIPTION
**Pull request by jimustafa**
This PR uses the [`fontawesome5` package](https://ctan.org/pkg/fontawesome5) in place of the icons and brand logos committed to the repository.

### CODE REVIEW

**Comment by rougier** [comment]
Nice, did not know font awesome was include in texlive.

**Comment by jimustafa** [comment]
Yeah, me neither. Always fun to discover a new package. A couple of the icons are slightly different than what was previously used, most notably the GitHub brand icon.

**Comment by jimustafa** [comment]
Hey @rouger, wanted to check if this PR was OK to merge. Let me know if anything needs to be addressed.

**Comment by jklymak** [comment]
I forget what the merge policy is here, is it just @rougier?

**Comment by jklymak** [comment]
ooops, sorry, meant to enter a comment that these look good, and nice to get rid of a repo dependency...

**Pull request merged**
