### PR TITLE
Typo fix in png Handout Tips (issue #45)

### PR DESCRIPTION
**Pull request by LouisJustinTALLOT**

### CODE REVIEW

**Comment by LouisJustinTALLOT** [comment]
I've modified the png on Paint.NET, not knowing which script to change ...

**Comment by jklymak** [comment]
I'll close.  Please modify the proper place in the scripts directory or on the tex.  Thanks!

**Comment by LouisJustinTALLOT** [comment]
This is the `.tex` so no error here : 

image

and I found no corresponding script, so I just wanted to change the `png` shown on the repo...

**Comment by jklymak** [comment]
The instructions for compiling are at the bottom of the ReadMe.md.

**Comment by rougier** [comment]
Can you explain what you changed on the PNG (such that we can change the corresponding latex file)?

**Comment by LouisJustinTALLOT** [comment]
> Can you explain what you changed on the PNG (such that we can change the corresponding latex file)?

Well I haven't seen that there were multiple typos in the last paragraph so I only changed the last one, `documentation` instead of `documenation`.

However, it appears that the corresponding tex file is clean of these typos as I have said on my previous comment :

> This is the `.tex` so no error here :
> 
> image
> 
> and I found no corresponding script, so I just wanted to change the `png` shown on the repo...

So I think only a rebuild of the files is needed, but I didn't find the time to download the fonts needed for that...

**Comment by rougier** [comment]
Thanks. I'll need to merge all pending PR and rebuild the cheat sheets (until it is done automatically).

**Pull request closed without merging**
