### PR TITLE
Consistent capitalization of section titles

### LINKED ISSUE #18: Consistent capitalization of section titles
Capitalization of section titles switches between all words starting with capital letters and only the first word starting with a capital letter; e.g.

- Quick start
- Ten Simple Rules
- Ticks & labels
- Scales & Projections

Choose one way and stick with it throughout.

Note: The Matplotlib docs only capitalize the first word of a section. I don't care if the cheat sheets use the same rule, as long as they are consistent within themselves.

### PR DESCRIPTION
**Pull request by timhoffm**
Closes #18.

### CODE REVIEW

**Comment by jklymak** [comment]
@rougier I'm not sure on the etiquette of this repository - normally I'd just merge a minor change like this in the main Matplotlib docs, but didn't want to do so here if that would be considered rude.

**Comment by rougier** [comment]
@jklymak For such small changes I would say it makes sense to merge them directly but I don't known what's the guideline for matplotlib.

**Comment by jklymak** [comment]
@rougier Thats what we usually do for the main matplotlib docs.  But if you wanted to carefully track any changes, happy to let you do final merges.  i.e. for mplcairo, @anntzer really does the final merges.

**Comment by rougier** [comment]
Let's follow matplotlib docs guidelines then.

**Pull request merged**
