### PR TITLE
Update for version 3.5.0

### PR DESCRIPTION
**Pull request by StefRe**
- make room for two additional annotation arrow styles (so that `'wedge'` is show again)
- add possibility to set tick labels together with tick positions

### CODE REVIEW

**Comment by jimustafa** [comment]
Good catch with the arrow styles. Missed that when I had bumped the matplotlib version in #101. Looks like v3.5.0 added two arrow styles. Maybe we should be checking that the number of subplots is consistent with the number of styles, should more be added to matplotlib in the future.

**Comment by StefRe** [comment]
@jimustafa As we don't have any unit tests here, we could do a "_manual integration test_" by [comparing](https://imagemagick.org/script/compare.php) the png converted output before and after changing matplotlib versions.

As simple

    compare https://web.archive.org/web/20211205002011im_/https://matplotlib.org/cheatsheets/_images/cheatsheets-2.png https://matplotlib.org/cheatsheets/_images/cheatsheets-2.png  diff.png

gives

diff

The webarchive version is of Dec 5, i.e. before merging #100, so `diff.png` also includes the cursive font fix, but it's just meant as an example to demonstrate the approach. (it also reveals some changes in the Garamond font of the bottom font example comparing small-caps vs normal, not sure where this comes from)

**Comment by rougier** [comment]
It's really nice to be able to compare like this.

**Review by jimustafa — APPROVED** [review]

**Comment by rougier** [comment]
@jimustafa Should we wait for your PR to be merged before mergin thos one or the other way around?

**Comment by jimustafa** [comment]
> @jimustafa Should we wait for your PR to be merged before mergin thos one or the other way around?

Free free to merge this one first. I can rebase #88, if necessary.

**Pull request merged**
