### PR TITLE
MNT: fix circle

### PR DESCRIPTION
**Pull request by jklymak**

### CODE REVIEW

**Comment by jimustafa** [comment]
I think the errors with circle are related to the python version being different from what was used when pinning the requirements. Given that the cheatsheets are more an "application" than a "library", the python version should probably be fixed. The requirements were originally generated with python 3.7.3, and it looks like python 3.9 was used in #83.

Can circle do something similar to gh actions (below), and specify the python version?
https://github.com/matplotlib/cheatsheets/blob/7ca0fd67602406906e3e576e8eaf9d9b7c7d9b6d/.github/workflows/main.yaml#L16-L18

**Comment by jklymak** [comment]
I mean, I'm sure its probably possible.  I wasn't planning to prioritize this, so maybe I'll move to draft.  @jimustafa if you wanted to take over trying to get this to work, I'd be great with that.  Otherwise, I'll try to circle back to it after 3.5.0 is released.

**Comment by jklymak** [comment]
(to be clear, my experience with CircleCI is copying other setups and googling - I'm not particularly knowledgeable!)

**Comment by jimustafa** [comment]
I can take a look at circle and try to get a config working. In the meantime, should we remove the circle config introduced in #83 to prevent the failed checks?

**Comment by jklymak** [comment]
I think so?  It was just to bootstrap being able to turn circle on at the project level for this repo.

**Comment by jklymak** [comment]
I just made the  circle test a placeholder from now.  Not sure what happens if we remove it altogether and then merge, if we need to reenable at the project level

**Comment by jklymak** [comment]
I'll self merge this to unbreak the build.  Note this is not user-facing...

**Pull request merged**
