### PR TITLE
Bump to Matplotlib 3.7.1

### LINKED ISSUE #116: Update for 3.6.0
This requires updating the Sphinx theme (e.g. matplotlib/mpl-third-party#134), but also auditing the plots to make sure they did not break or could be using newer stuff.

### LINKED ISSUE #124: Cartopy version
@jimustafa what was the reason for pinning cartopy to `0.19.0.post1` in dbf92ab? It seems to work with any (newer) version too.

### PR DESCRIPTION
**Pull request by QuLogic**
And also Cartopy to latest version to make it installable on current versions of Python.

Fixes #116 
Fixes #124

### CODE REVIEW

**Comment by QuLogic** [comment]
Possible things to investigate after finishing the build locally:
- Beginners:
    - Edges around `scatter`, `bar`, `pie`, `hist`, and `boxplot` are not exactly the same size
- Intermediate:
    - Edges around anatomy circles are missing
    - Sine and Cosine figure appears to be a bit taller
- Tips:
    - Random data in transparency section seems completely different

Some similar problems occur in the 2-page version.

**Comment by QuLogic** [comment]
Also note that the anatomy example has changed somewhat in Matplotlib: https://github.com/matplotlib/matplotlib/compare/v3.5.0..v3.7.1#diff-d476362ab30b16055b90f54100d51a2d0e479f1f886bbf371f2008f734bb9ef8; not sure if we want to bring those changes over here.

**Comment by QuLogic** [comment]
Looking at the results from the build:
- On cheatsheets p1, `seaborn-notebook` -> `seaborn-v0_8-notebook` is a little too wide, but still visible. cheatsheets-1-diff
- On cheatsheets p2, the Axes in the `imshow` example, Image Interpolation section, and Annotation connection styles section are now compressed closer. cheatsheets-2-diff
- On the intermediate handout, there are minor shifts because the Sine and Cosine figure is a little bit taller. handout-intermediate-diff
- On the tips-and-tricks handout, the random results in the Transparency section have changed; it doesn't appear to have a seed. handout-tips-diff

Please ignore all my previous comments about local differences, as they appear to be _local_ to my machine and not specific to this change.

**Comment by QuLogic** [comment]
Also, looking at the build a bit closer, it appears that `figures/legend.pdf` changed because it was re-cropped, but that's not a real change, so I will revert that.

**Comment by QuLogic** [comment]
With #126 in, the tip-and-tricks diff is now:
handout-tips-diff

**Comment by QuLogic** [comment]
IIRC, we stopped counting invisible ticks in tight layout at some point, which is likely the reason the Axes were clipped closer, and thus appear a bit bigger now.

**Comment by QuLogic** [comment]
Rebased, but note the above comment: https://github.com/matplotlib/cheatsheets/pull/125#issuecomment-1486496327

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
> Rebased, but note the above comment: [#125 (comment)](https://github.com/matplotlib/cheatsheets/pull/125#issuecomment-1486496327)

Theoretically yes. But that doesn't have to be within this PR. And please check weather. It's still readable - if I see it correctly, we have added more content.

**Review by dstansby — APPROVED** [review]

**Pull request merged**
