### PR TITLE
Add image diffs against previous build to CI results

### PR DESCRIPTION
**Pull request by QuLogic**
Unfortunately, from what I've read, you can't upload an image from Actions, so you still need to download the build artifact to see the diff, but it's one less step to do yourself manually.

### CODE REVIEW

**Comment by QuLogic** [comment]
> you still need to download the build artifact to see the diff

i.e., it's part of the `build` Artifact at the bottom of the Check: https://github.com/matplotlib/cheatsheets/actions/runs/4552134723?pr=130

**Comment by dstansby** [comment]
I've merged `master` here to fire CI since the old artifacts had expired.

**Comment by QuLogic** [comment]
OK, I moved it to a separate artifact to make it easier to find. Now with artifacts v4, we can generate a URL, and with [build step summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/), we can put that all on the summary.

So you can see the summary dropped here: https://github.com/matplotlib/cheatsheets/actions/runs/7706808370#summary-21002939154

**Review by dstansby — APPROVED** [review]

**Comment by QuLogic** [comment]
I think the only way to do that would be to move it into a separate job that depends on the build one, download the artifacts from it, and run comparison from there.

**Comment by dstansby** [comment]
I think worth getting this in as is - I opened https://github.com/matplotlib/cheatsheets/issues/143 for making the diff check a seaparate run.

**Pull request merged**
